### ISSUE TITLE
Povoar banco de dados de staging com dados dummy

### ISSUE THREAD

**Issue by mauodias** [hackathon-da-diversidade/agencia-compromisso#17]
_Depende de: #14, #16_ 

Para que possamos testar a aplicação no futuro, precisamos povoar a base de dados de staging com dados falsos, porém na estrutura esperada pela aplicação.

**ACs:**
- A base de dados de staging está povoada e é usável.

**Comment by mauodias** [comment]
Podemos usar algum dos serviços abaixo:
- https://www.generatedata.com
- https://mockaroo.com

Não sei como funcionam, mas parecem atender nossa necessidade. Google me retornou uma penca, esses são só os dois primeiros resultados

**Comment by ingridmurielem** [comment]
Achei esse mockaroo interessante, vou dar uma investigada nele
